server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**

            - id: course-service
              uri: lb://course-service
              predicates:
                - Path=/api/courses/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/