server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # ---------------------------------------------------
            # 1. ROUTE FOR AUTHENTICATION (PUBLIC - NO FILTER)
            # ---------------------------------------------------
            - id: auth-route
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/auth/**

            # ---------------------------------------------------
            # 2. ROUTE FOR USER SERVICE (SECURED)
            # ---------------------------------------------------
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
              filters:
                - Authentication

            # ---------------------------------------------------
            # 3. ROUTE FOR COURSE SERVICE (SECURED)
            # ---------------------------------------------------
            - id: course-service
              uri: lb://COURSE-SERVICE
              predicates:
                - Path=/api/courses/**
              filters:
                - Authentication