server:
  port: 8761 # Default port for Eureka Server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # We don't want the server to register itself
    fetch-registry: false # The server doesn't need to fetch its own registry
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: discovery-server # The name of this microservice